sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-utils

script:
  - docker-compose build
  - docker-compose up -d
  - sleep 25
  - curl localhost:9000/all
  - curl localhost:9000/docs
  - curl -s http://localhost:9000/mensen | python -m json.tool >/dev/null
  - curl -s http://localhost:9000/menu/70ad738c960cc5e88e5e8d8ac1b5975e | python -m json.tool >/dev/null
  - curl -s http://localhost:9000/openmensa/canteen/70ad738c960cc5e88e5e8d8ac1b5975e | xmllint --noout -
  - curl -s http://localhost:9000/openmensa/today/70ad738c960cc5e88e5e8d8ac1b5975e | xmllint --noout -
  - curl -s http://localhost:9000/v2/menu/ | python -m json.tool >/dev/null
  - curl -s http://localhost:9000/v2/menu/canteen/d46d2d2c4b3ea6341254a9649e38678f | python -m json.tool >/dev/null
  - curl -s http://localhost:9000/v2/menu/today/d46d2d2c4b3ea6341254a9649e38678f | python -m json.tool >/dev/null